# Generated by Django 5.0.2 on 2024-08-01 12:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_create', models.DateField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
