# Generated by Django 5.0.2 on 2024-08-01 12:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreate',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcreate',
            name='date_create',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
