# Generated by Django 5.0.2 on 2024-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_api', '0006_alter_task_shared_with_alter_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
