# Generated by Django 5.0.2 on 2024-08-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_api', '0007_alter_task_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskaccess',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='taskaccess',
            name='can_update',
        ),
    ]
